export const langConfig = {
  jp: {
    homeview: {
      announcement: '公告：本サイトのエピソード',
      announcement1: 'いらっしゃります,',
      announcement2: 'dmlのサイトへ。',
      announcement3: '普通な普通なプログラマーとして、ここで生活や推し活を記録してる。',
      contents: [
        '普通のエンジニアとして、特別に優れた技術があるわけではありませんが、フロントエンドの勉強の一環として、このサイトを作ってみました。',
        'アニメやゲームなどの二次元文化が好きで、J-POPにも触れるようになりました。ある出来事をきっかけに、J-POPアイドルを追いかけるようになりました。',
        'ライブに行ったり、CDを買ったりするために、2023年から日本語の勉強を始めました。週2回、仕事終わりに日本語教室に通い、1年間で『標準日本語 中級』を学び終えました。その後、なんとなく受けた日本語能力試験で、気がつけばN1に合格していました。',
        'そして、日本への渡航を決意。',
        'ちょっと変わったきっかけではありますが、現在は日本で社会人として働いています！',
      ],
    },
    miletHomeView: {
      title0: 'miletについて',
      title1: 'milet写真集 Gallery',
      title2: 'miletの活動軌跡',
      title3: 'miletの公式サイト',
      title4: 'miletの公式SNS',
    },
    songGuess: {
      homeTitle: 'Song Guess Challenge',
      homeDescription: '新しいインタラクティブなエコールーム。難易度を選び、音源を聴いて、制限時間内に曲名を当てます。',
      homeCta: '曲当てに挑戦',
      homeMeta: '10問 / 即時フィードバック',
      introEyebrow: 'echo room',
      introTitle: 'Song Guess Challenge',
      introLead: 'miletの楽曲クリップを聴いて、カウントダウンが終わる前に正しい曲名を選びます。',
      introSub: '各難易度は10問です。解答後すぐに正誤が表示され、挑戦ごとに利用可能な問題セットからランダムに選ばれます。',
      setupEyebrow: 'challenge setup',
      setupTitle: '難易度を選択',
      loadConfigError: '問題データを読み込めませんでした。時間をおいて再度お試しください。',
      createError: 'チャレンジの作成に失敗しました。時間をおいて再度お試しください。',
      start: 'スタート',
      preparing: '準備中...',
      questionsBadge: '10 questions',
      randomBankBadge: 'random bank',
      feedbackBadge: 'instant feedback',
      audioSuffix: 's audio',
      difficultyDetail: '{timeLimit}秒で解答 / {optionCount}択',
      loadingChallenge: 'Loading challenge...',
      challengeSuffix: 'challenge',
      question: 'Question',
      pause: 'Pause',
      play: 'Play',
      correct: 'Correct',
      answerPrefix: 'Answer:',
      timeUp: 'Time up',
      playHint: '再生後にカウントダウンが始まり、送信後すぐに結果が表示されます。',
      checking: 'Checking...',
      submit: '解答を送信',
      viewResult: '結果を見る',
      nextQuestion: '次の問題',
      challengeError: 'チャレンジが存在しないか、期限切れです。',
      audioError: '音声の再生に失敗しました。もう一度お試しください。',
      answerError: '解答の送信に失敗しました。もう一度お試しください。',
      loadingResult: 'Loading result...',
      resultEyebrow: 'song guess result',
      copied: '共有内容をコピーしました',
      share: '結果を共有',
      retry: 'もう一度挑戦',
      home: 'Homeへ戻る',
      resultError: '結果が存在しないか、期限切れです。',
      yourChoice: 'あなたの選択：',
      perfect: 'Perfect echo',
      clear: 'Clear memory',
      almost: 'Almost there',
      keep: 'Keep listening',
      replay: 'Replay the echoes',
    },

    miletPic: {
      tip: '当サイトに掲載している画像の一部は、インタネットやMVから引用しています。FCの限定画像についてはできるだけ掲載しないように気を付けていますが、もし見落としがあったらごめんなさい！！',
    },
    miletGallery: {
      tip: '当サイトに掲載している画像の一部は、インタネットやMVから引用しています。FCの限定画像についてはできるだけ掲載しないように気を付けていますが、もし見落としがあったらごめんなさい！！',
      topAlbums: 'ピックアップアルバム',
      albums: 'すべてのアルバム',
      toptip: '固定アルバム',
    },
  },
  zh: {
    homeview: {
      announcement: '公告：关于本站的小故事',
      announcement1: '欢迎来到',
      announcement2: 'dml 的小站',
      announcement3:
        '，一个普通的在日码农。这里记录生活片段、追星旅程与学习过程，希望你在这里也能找到共鸣。',
      contents: [
        '作为一个普通的不能再普通的码农，技术称不上很强，学习前端顺便创建了这个网站。',
        '个人是喜欢动漫，游戏，也接触j-pop，某件事为契机开始追星j-pop。',
        '为了方便追live买CD，2023年开始学习日语。一周2节课,下班之后去日语教室，为期一年的课程学完了标准日本语中级。之后又莫名其妙的情况下考过了N1',
        '然后踏上了赴日之旅。',
        '虽然赴日动机比较奇怪，目前也是在日社畜一枚！！！',
      ],
    },
    miletHomeView: {
      title0: '关于milet',
      title1: '照片集 Gallery',
      title2: ' milet活动轨迹',
      title3: 'milet官方网站',
      title4: 'milet官方SNS',
    },
    songGuess: {
      homeTitle: 'Song Guess Challenge',
      homeDescription: '新增的互动回声室。选择难度，听一段音频，在倒计时结束前猜出是哪首歌。',
      homeCta: '开始听歌识曲',
      homeMeta: '10 questions / instant feedback',
      introEyebrow: 'echo room',
      introTitle: 'Song Guess Challenge',
      introLead: '听一段 milet 的歌曲片段，在倒计时结束前选择正确曲目。',
      introSub: '每个难度 10 题，提交后立刻反馈结果。每次挑战会从当前可用题库中随机抽取一套题库。',
      setupEyebrow: 'challenge setup',
      setupTitle: '选择难度',
      loadConfigError: '互动题库暂时无法加载，请稍后再试。',
      createError: '挑战创建失败，请稍后再试。',
      start: '开始挑战',
      preparing: 'Preparing...',
      questionsBadge: '10 questions',
      randomBankBadge: 'random bank',
      feedbackBadge: 'instant feedback',
      audioSuffix: 's audio',
      difficultyDetail: '{timeLimit} 秒答题 / {optionCount} 个选项',
      loadingChallenge: 'Loading challenge...',
      challengeSuffix: 'challenge',
      question: 'Question',
      pause: 'Pause',
      play: 'Play',
      correct: 'Correct',
      answerPrefix: 'Answer:',
      timeUp: 'Time up',
      playHint: '播放后倒计时开始，提交后会立即反馈。',
      checking: 'Checking...',
      submit: '提交答案',
      viewResult: '查看结果',
      nextQuestion: '下一题',
      challengeError: '挑战不存在或已过期。',
      audioError: '音频播放失败，请重试。',
      answerError: '答案提交失败，请重试。',
      loadingResult: 'Loading result...',
      resultEyebrow: 'song guess result',
      copied: '已复制分享',
      share: '分享结果',
      retry: '再次挑战',
      home: '回到 Home',
      resultError: '结果不存在或已过期。',
      yourChoice: '你的选择：',
      perfect: 'Perfect echo',
      clear: 'Clear memory',
      almost: 'Almost there',
      keep: 'Keep listening',
      replay: 'Replay the echoes',
    },

    miletPic: {
      tip: '提示：本站图片部分来自网络、MV；尽可能避免fc图片外泄，可能会有漏网之鱼',
    },
    miletGallery: {
      tip: '提示：本站图片部分来自网络、MV；尽可能避免fc图片外泄，可能会有漏网之鱼',
      topAlbums: '精选相册',
      albums: '所有相册',
      toptip: '置顶相册',
    },
  },
} as LangConfig
